### ISSUE TITLE
Proper comments?

### ISSUE THREAD

**Issue by alex-paul-htm** [Alriceee/snake.multiplayer#1]
I want to reverse engineer this game so I can modify it, can you properly comment on the scripts. if not ill just take a little longer.

**Comment by alex-paul-htm** [comment]
@Alriceee plz respond, I need to make a sneek version of this

**Comment by Alriceee** [comment]
> I want to reverse engineer this game so I can modify it, can you properly comment on the scripts. if not ill just take a little longer.

absoutly not lol
